---
title: "Introduction"
author: "Taylor Mattia"
date: "December 17, 2017"
output: html_document
---

## Introduction 


In this project, I attempt to create networks of county-to-county migration in the United States based on data from the American Community Survey (ACS) adminstered via the U.S. Census (<https://www.census.gov/topics/population/migration/guidance/county-to-county-migration-flows.html>).  Each network is constructed over a five-year time period, as the American Community Survey is conducted every five years. I construct seperate networks for the following time intervals: 2005-2009, 2006-2010, 2007-2011, 2008 - 2012, 2009-2013, 2010 - 2015, and 2011 - 2015. For each county in the network, I also have ACS estimates pertaining to household income, poverty, unemployment, high school graduation rates, total population, and racial demographic information of county residents. My goal is to see whether county covariate information can predict where people are moving from and where people are moving to. 

* Part 1: Network Construction and Data Cleaning 

Initially, the project involves rearranging data from the ACS so that it could be used by packages in R such as igraph and statnet for later analysis. To do so, I clean the data ('ACS0615.R') such that for each time interval mention, I have an edgelist in which the first column is the county individuals are moving from (the "sending" county"), the second column signifies the county individuals are moving to (the "receiving county"), and the third column is a number that indicates the number of people who moved from the sending to the receiving county (e.g. 'states0509.Rdata'). Then, I matched each county in the data set with the covariate information mentioned in the introduction. I have yearly ACS estimates for all covariates from 2009-2015. Each set of yearly estimates (e.g. poverty rates in 2009) are a separate .csv file (e.g. 'poverty2009.csv'). I clean the data ('Covariate.R') and attach them as vertex attributes to each county in the network.

* Part 2: Network Visualization and Summary Statistics

After each network is constructed, I provide some examples about how migration data can be visualized (see    http://kateto.net/network-visualization for further details). Using the 2011-2015 network as a baseline, I am able to produce visualizations of intra-state migration (/Migration Data/texas.png), migration to a particular state from other parts of the U.S. (/Migration Data/colarado.png), and migration from one county to all other counties in a given time interval (/Migration Data/nyc.png). I also calculate the following summary statistics for each county in the 2011-2015 network: total, in, and out degree, degree prestige, status prestige, and eigen vector centrality. I do this for two sets of edges. In the first set, each edge is weighted and equals the total number of people who moved from the sending to the receiving county. In the second set, each edge is also weighted and equals the total number of people who moved from the sending to the receiving county divided by the total number of people in the receiving county. Therefore, I can observe which counties are more central in the aggregate (set 1) and per capita (set 2)


* Part 3:Network Estimation 

Lastly, I attempt to see whether certain covariate information is able to predict the probability of a weighted edge between a sending and receiving county. Originally, I planned to do this using exponential random graph models (ERGMs), but had difficulty with convergence given the size of the network and ERGM's treatment (or lack thereof) with valued networks. Therefore, I estimate a p1 model, assuming that each edge is independent of all other edges in the network. Using the 2011-2015 network, I induce a subgraph that includes only migration within the state of Texas to assess whether county covariate information such as unemployment, household income, percentage of the county that is white and Latino, or the high school graduation rate at both the sender and receiver level in 2010 can predict migration between 2011 and 2015. 
